apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gogs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gogs.labels" . | indent 4 }}
type: Opaque
stringData:
  app.ini: |-
{{- range $key, $value := index .Values "app.ini" }}
{{- if not (eq $key "default") }}
    [{{ $key }}]
{{- end }}
    {{- range $elem, $elemVal := $value }}
    {{ $elem | snakecase | upper }} = {{ $elemVal }}
    {{- end }}
{{- end }}
