{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gogs.fullname" . }}
  labels:
{{ include "gogs.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end }}
