apiVersion: v1
description: 'Gogs: Go Git Service'
name: gogs
version: 0.8.0
appVersion: 0.11.91
home: https://gogs.io/
icon: https://gogs.io/img/favicon.ico
maintainers:
  - name: rtluckie
    email: rtluckie@users.noreply.github.com
keywords:
- git
