# Default values for gogs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

rbac:
  create: true
  pspEnabled: false
  pspUseAppArmor: false
  namespaced: false

serviceAccount:
  create: true
  name:

image:
  repository: gogs/gogs
  tag: 0.11.91
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  httpPort: 80
  httpTargetPort: 3000
  sshPort: 22
  sshTargetPort: 22
  annotations: {}
  labels: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName:

## Extra environment variables that will be pass onto deployment pods
env: {}

## The name of a secret in the same kubernetes namespace which contain values to be added to the environment
## This can be useful for auth tokens, etc
envFromSecret: ""

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName: "default-scheduler"

## Assign a PriorityClassName to pods if set
# priorityClassName:

deploymentStrategy:
  type: RollingUpdate

persistence:
  enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  ##
  # existingClaim: "-"
  ## gogs data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 1Gi

postgresql:

  ### Install PostgreSQL dependency
  install: true

  ### PostgreSQL User to create.
  postgresUser: gogs

  ## PostgreSQL Password for the new user.
  ## If not set, a random 10 characters password will be used.
  postgresPassword: gogs

  ## PostgreSQL Database to create.
  postgresDatabase: gogs

  ## PostgreSQL SSL Mode
  postgresSSLMode: disable

  ## Persistent Volume Storage configuration.
  ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  persistence:
    ## Enable PostgreSQL persistence using Persistent Volume Claims.
    ##
    enabled: true


tolerations: []

affinity: {}

app.ini:
  default:
    appName: 'gogs'
  server:
    protocol: 'http'
